-- MySQL Script generated by MySQL Workbench
-- Fri May 31 07:57:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema assu_camping
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assu_camping
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assu_camping` DEFAULT CHARACTER SET utf8 ;
USE `assu_camping` ;

-- -----------------------------------------------------
-- Table `assu_camping`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Info_garantie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Info_garantie` (
  `idInfo_garantie` INT NOT NULL AUTO_INCREMENT,
  `frais` VARCHAR(45) NOT NULL,
  `debut` DATE NOT NULL,
  `duree` INT NOT NULL,
  PRIMARY KEY (`idInfo_garantie`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Fournisseur` (
  `idFournisseur` INT NOT NULL AUTO_INCREMENT,
  `Fournisseurs` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFournisseur`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Prix_vente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Prix_vente` (
  `idPrixVente` INT NOT NULL AUTO_INCREMENT,
  `assistance` TINYINT NOT NULL,
  `dateCreation` DATE NOT NULL,
  `typeContrat` VARCHAR(45) NOT NULL,
  `duree` INT NOT NULL,
  `prix` DECIMAL(10,2) NOT NULL,
  `idFournisseur` INT NOT NULL,
  PRIMARY KEY (`idPrixVente`),
  INDEX `fk_Tarif_Fournisseur1_idx` (`idFournisseur` ASC) ,
  CONSTRAINT `fk_Tarif_Fournisseur1`
    FOREIGN KEY (`idFournisseur`)
    REFERENCES `assu_camping`.`Fournisseur` (`idFournisseur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Prix_Achat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Prix_Achat` (
  `idPrixAchat` INT NOT NULL AUTO_INCREMENT,
  `assistance` TINYINT NOT NULL,
  `dateCreation` DATE NOT NULL,
  `typeContrat` VARCHAR(45) NOT NULL,
  `duree` INT NOT NULL,
  `prix` DECIMAL(10,2) NOT NULL,
  `idFournisseur` INT NOT NULL,
  PRIMARY KEY (`idPrixAchat`),
  INDEX `fk_Tarif_Fournisseur1_idx` (`idFournisseur` ASC) ,
  CONSTRAINT `fk_Tarif_Fournisseur10`
    FOREIGN KEY (`idFournisseur`)
    REFERENCES `assu_camping`.`Fournisseur` (`idFournisseur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Pays` (
  `idPays` INT NOT NULL,
  `code` INT NOT NULL,
  `alpha2` VARCHAR(2) NOT NULL,
  `alpha3` VARCHAR(3) NOT NULL,
  `nom_en_gb` VARCHAR(45) NOT NULL,
  `nom_fr_fr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPays`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Info_conducteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Info_conducteur` (
  `idInfo_conducteur` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(10) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telephone` INT NOT NULL,
  `numRue` INT NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `numPermis` INT NOT NULL,
  `datePermis` DATE NOT NULL,
  `paysPermis` VARCHAR(45) NOT NULL,
  `idPays` INT NOT NULL,
  PRIMARY KEY (`idInfo_conducteur`),
  INDEX `fk_Info_conducteur_Pays1_idx` (`idPays` ASC) ,
  CONSTRAINT `fk_Info_conducteur_Pays1`
    FOREIGN KEY (`idPays`)
    REFERENCES `assu_camping`.`Pays` (`idPays`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Version` (
  `idVersion` INT NOT NULL AUTO_INCREMENT,
  `version` VARCHAR(45) NOT NULL,
  `carrosserie` VARCHAR(45) NOT NULL,
  `puissanceFisc` VARCHAR(45) NOT NULL,
  `energie` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idVersion`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Info_vehicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Info_vehicule` (
  `idInfo_vehicule` INT NOT NULL AUTO_INCREMENT,
  `marque` VARCHAR(30) NOT NULL,
  `modele` VARCHAR(32) NOT NULL,
  `paysOrigine` VARCHAR(45) NOT NULL,
  `poids` TINYINT NOT NULL,
  `immatriculation` VARCHAR(12) NOT NULL,
  `dateMEC` DATE NOT NULL,
  `nombrePlace` INT NOT NULL,
  `numIdentif` INT NOT NULL,
  `idVersion` INT NOT NULL,
  `idPays` INT NOT NULL,
  PRIMARY KEY (`idInfo_vehicule`),
  INDEX `fk_Info_vehicule_Version1_idx` (`idVersion` ASC) ,
  INDEX `fk_Info_vehicule_Pays1_idx` (`idPays` ASC) ,
  CONSTRAINT `fk_Info_vehicule_Version1`
    FOREIGN KEY (`idVersion`)
    REFERENCES `assu_camping`.`Version` (`idVersion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Info_vehicule_Pays1`
    FOREIGN KEY (`idPays`)
    REFERENCES `assu_camping`.`Pays` (`idPays`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Contrat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Contrat` (
  `idContrat` INT NOT NULL AUTO_INCREMENT,
  `assistance` TINYINT NOT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `typeContrat` VARCHAR(45) NOT NULL,
  `dateCreation` DATETIME NOT NULL,
  `prixTotal` DECIMAL(10,2) NOT NULL,
  `idInfo_garantie` INT NOT NULL,
  `idPrixVente` INT NOT NULL,
  `idPrixAchat` INT NOT NULL,
  `idInfo_conducteur` INT NOT NULL,
  `idInfo_vehicule` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idContrat`),
  INDEX `fk_Contrat_Info_garantie1_idx` (`idInfo_garantie` ASC) ,
  INDEX `fk_Contrat_Prix_vente1_idx` (`idPrixVente` ASC) ,
  INDEX `fk_Contrat_Prix_Achat1_idx` (`idPrixAchat` ASC) ,
  INDEX `fk_Contrat_Info_conducteur1_idx` (`idInfo_conducteur` ASC) ,
  INDEX `fk_Contrat_Info_vehicule1_idx` (`idInfo_vehicule` ASC) ,
  INDEX `fk_Contrat_Utilisateur1_idx` (`idUtilisateur` ASC) ,
  CONSTRAINT `fk_Contrat_Info_garantie1`
    FOREIGN KEY (`idInfo_garantie`)
    REFERENCES `assu_camping`.`Info_garantie` (`idInfo_garantie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrat_Prix_vente1`
    FOREIGN KEY (`idPrixVente`)
    REFERENCES `assu_camping`.`Prix_vente` (`idPrixVente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrat_Prix_Achat1`
    FOREIGN KEY (`idPrixAchat`)
    REFERENCES `assu_camping`.`Prix_Achat` (`idPrixAchat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrat_Info_conducteur1`
    FOREIGN KEY (`idInfo_conducteur`)
    REFERENCES `assu_camping`.`Info_conducteur` (`idInfo_conducteur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrat_Info_vehicule1`
    FOREIGN KEY (`idInfo_vehicule`)
    REFERENCES `assu_camping`.`Info_vehicule` (`idInfo_vehicule`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrat_Utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `assu_camping`.`Utilisateur` (`idUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Mode_paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Mode_paiement` (
  `idMode_paiement` INT NOT NULL AUTO_INCREMENT,
  `moyenPaiement` VARCHAR(45) NOT NULL,
  `refPaiement` INT NOT NULL,
  `dateValidite` DATE NOT NULL,
  `idContrat` INT NOT NULL,
  PRIMARY KEY (`idMode_paiement`),
  INDEX `fk_Mode_paiement_Contrat1_idx` (`idContrat` ASC) ,
  CONSTRAINT `fk_Mode_paiement_Contrat1`
    FOREIGN KEY (`idContrat`)
    REFERENCES `assu_camping`.`Contrat` (`idContrat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Facture` (
  `idFacture` INT NOT NULL AUTO_INCREMENT,
  `dateFacture` DATE NOT NULL,
  `totalFacture` DECIMAL(10,2) NOT NULL,
  `idContrat` INT NOT NULL,
  PRIMARY KEY (`idFacture`),
  INDEX `fk_Facture_Contrat1_idx` (`idContrat` ASC) ,
  CONSTRAINT `fk_Facture_Contrat1`
    FOREIGN KEY (`idContrat`)
    REFERENCES `assu_camping`.`Contrat` (`idContrat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assu_camping`.`Documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Documents` (
  `idDocument` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `abrevation` VARCHAR(10) NOT NULL,
  `lien` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDocument`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Paiement` (
  `idPaiement` INT NOT NULL AUTO_INCREMENT,
  `reglement` TINYINT NOT NULL,
  `reçuTPE` VARCHAR(45) NOT NULL,
  `jourReglement` DATE NOT NULL,
  `idContrat` INT NOT NULL,
  PRIMARY KEY (`idPaiement`),
  INDEX `fk_Paiement_Contrat1_idx` (`idContrat` ASC) ,
  CONSTRAINT `fk_Paiement_Contrat1`
    FOREIGN KEY (`idContrat`)
    REFERENCES `assu_camping`.`Contrat` (`idContrat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Prix_vente_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Prix_vente_option` (
  `idPrixVenteOption` INT NOT NULL AUTO_INCREMENT,
  `assistance` TINYINT NOT NULL,
  `dateCreation` DATE NOT NULL,
  `typeContrat` VARCHAR(45) NOT NULL,
  `duree` INT NOT NULL,
  `prix` DECIMAL(10,2) NOT NULL,
  `idFournisseur` INT NOT NULL,
  PRIMARY KEY (`idPrixVenteOption`),
  INDEX `fk_Tarif_Fournisseur1_idx` (`idFournisseur` ASC) ,
  CONSTRAINT `fk_Tarif_Fournisseur11`
    FOREIGN KEY (`idFournisseur`)
    REFERENCES `assu_camping`.`Fournisseur` (`idFournisseur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Prix_achat_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Prix_achat_option` (
  `idPrixAchatOption` INT NOT NULL AUTO_INCREMENT,
  `assistance` TINYINT NOT NULL,
  `dateCreation` DATE NOT NULL,
  `typeContrat` VARCHAR(45) NOT NULL,
  `duree` INT NOT NULL,
  `prix` DECIMAL(10,2) NOT NULL,
  `idFournisseur` INT NOT NULL,
  PRIMARY KEY (`idPrixAchatOption`),
  INDEX `fk_Tarif_Fournisseur1_idx` (`idFournisseur` ASC) ,
  CONSTRAINT `fk_Tarif_Fournisseur110`
    FOREIGN KEY (`idFournisseur`)
    REFERENCES `assu_camping`.`Fournisseur` (`idFournisseur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Documents_has_Contrat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Documents_has_Contrat` (
  `idDocument` INT NOT NULL,
  `idContrat` INT NOT NULL,
  PRIMARY KEY (`idDocument`, `idContrat`),
  INDEX `fk_Documents_has_Contrat_Contrat1_idx` (`idContrat` ASC) ,
  INDEX `fk_Documents_has_Contrat_Documents1_idx` (`idDocument` ASC) ,
  CONSTRAINT `fk_Documents_has_Contrat_Documents1`
    FOREIGN KEY (`idDocument`)
    REFERENCES `assu_camping`.`Documents` (`idDocument`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Documents_has_Contrat_Contrat1`
    FOREIGN KEY (`idContrat`)
    REFERENCES `assu_camping`.`Contrat` (`idContrat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `assu_camping`.`Contrat_has_Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assu_camping`.`Contrat_has_Option` (
  `idContrat` INT NOT NULL,
  `idPrixVenteOption` INT NOT NULL,
  `idPrixAchatOption` INT NOT NULL,
  PRIMARY KEY (`idContrat`, `idPrixVenteOption`, `idPrixAchatOption`),
  INDEX `fk_Contrat_has_Prix_vente_option_Prix_vente_option1_idx` (`idPrixVenteOption` ASC) ,
  INDEX `fk_Contrat_has_Prix_vente_option_Contrat1_idx` (`idContrat` ASC) ,
  INDEX `fk_Contrat_has_Prix_vente_option_Prix_achat_option1_idx` (`idPrixAchatOption` ASC) ,
  CONSTRAINT `fk_Contrat_has_Prix_vente_option_Contrat1`
    FOREIGN KEY (`idContrat`)
    REFERENCES `assu_camping`.`Contrat` (`idContrat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrat_has_Prix_vente_option_Prix_vente_option1`
    FOREIGN KEY (`idPrixVenteOption`)
    REFERENCES `assu_camping`.`Prix_vente_option` (`idPrixVenteOption`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrat_has_Prix_vente_option_Prix_achat_option1`
    FOREIGN KEY (`idPrixAchatOption`)
    REFERENCES `assu_camping`.`Prix_achat_option` (`idPrixAchatOption`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
